name = "andrii_seeker"
version = "0.0.1"
authors = [
  { name="Andrii Svitelskyi", email="andriy.svitelskyi@gmail.com" },
]
description = "Cleand Folder"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Windows",
]

"Homepage" = "https://github.com/andriyseeker22856/CleanFolder_App"